# --- Model Configuration ---
model_name: 'yolo11m-seg' 
weights: 'yolo11m.pt'  # Path to the pre-trained weights file

# --- Dataset Configuration ---
data: datasets/converted/yamaha_seg1/dataset.yaml  # Path to the dataset YAML file

# --- Training Loop Control ---
epochs: 100
patience: 50

# --- Optimizer Settings ---
optimizer: 'AdamW'
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005

# --- Batching and Image Size ---
batch: 8
imgsz: [1024, 544]

# --- Augmentation Parameters ---
# augment: false
# hsv_h: 0.015
# hsv_s: 0.7
# hsv_v: 0.4
# degrees: 0.0
# translate: 0.1
# scale: 0.5
# shear: 0.0
# perspective: 0.0
# flipud: 0.0
# fliplr: 0.5
# mosaic: 1.0
# mixup: 0.0
# copy_paste: 0.0

# --- Logging, Saving, and Output ---
project: "runs/yolo11m-seg_exp"
name: "yamaha-seg_cfg2_exp"
exist_ok: false
save: true
save_period: -1

# --- Hardware and Environment ---
device: ''
workers: 8