study_name: 'yolo11n-seg-tune'  # Name of the Optuna study

# --- Model Configuration --- #
model_name: 'yolo11n-seg' 
weights: 'yolo11n-seg.pt'  # Path to the pre-trained weights file

project: 'runs/optuna_tunes2'  # Project name for saving results
n_trials: 10  # Number of trials for hyperparameter tuning
name: 'yolo11n-seg-tune'  # Name of the experiment

# --- Dataset Configuration --- #
data: datasets/converted/yamaha_seg1/dataset.yaml  # Path to the dataset YAML file

# --- Other Configuration --- #
epochs: 100 # Total number of training epochs
time: null
patience: 50 # Early stopping patience

save: True # Save model checkpoints
save_period: -1 # Save model every epoch
cache: False # Cache images for faster training
device: null # Device to use for training, e.g., 'cuda:0' or 'cpu'
workers: 8 # Number of data loading workers
exist_ok: False # Allow overwriting existing results
pretrained: True # Use pre-trained weights

optimizer: 'AdamW'
seed: 0 # Random seed for reproducibility
deterministic: True
single_cls: False # Single class training
rect: True
multi_scale: False
cos_lr: False
close_mosaic: 10
resume: False # Resume training from a checkpoint
amp: True # Use Automatic Mixed Precision
fraction: 1.0 # Fraction of the dataset to use for training
profile: False
freeze: null # Freeze layers during training, e.g., 'backbone', 'head'

box: 7.5              # Box loss gain
nbs: 64               # Nominal batch size for scaling hyperparameters (non-tunable)
overlap_mask: True    # Use overlap mask for segmentation
mask_ratio: 4         # Ratio of mask to image size
dropout: 0.0          # Dropout rate
val: True             # Validate during training
plots: True           # Save training plots

# --- Tunable Hyperparameters Settings --- #
# Default hyperparameters for the model

imgsz: [1024, 544] # Input image size for training
batch: 16 # Batch size for training

lr0: 0.01             # Initial learning rate
lrf: 0.01             # Final learning rate multiplier
momentum: 0.937       # SGD momentum
weight_decay: 0.0005  # L2 regularization
warmup_epochs: 3.0    # Warmup epochs duration
warmup_momentum: 0.8  # Initial momentum during warmup
warmup_bias_lr: 0.1   # Initial bias learning rate during warmup
cls: 0.5              # Classification loss gain
dfl: 1.5              # DFL loss gain

hsv_h: 0.015          # Hue augmentation (fraction)
hsv_s: 0.7            # Saturation augmentation (fraction)
hsv_v: 0.4            # Value augmentation (fraction)
degrees: 0.0          # Rotation augmentation (degrees)
translate: 0.1        # Translation augmentation (fraction)
scale: 0.5            # Scale augmentation (log scale)
shear: 0.0            # Shear augmentation (degrees)
perspective: 0.0      # Perspective augmentation (fraction)
flipud: 0.0           # Vertical flip probability
fliplr: 0.5           # Horizontal flip probability
bgr: 0.0              # BGR augmentation probability
mosaic: 1.0           # Mosaic augmentation probability
mixup: 0.0            # Mixup augmentation probability
cutmix: 0.0           # CutMix augmentation probability
copy_paste: 0.0       # Copy-paste augmentation probability
copy_paste_mode: 'flip'
auto_augment: 'randaugment'
erasing: 0.4          # Erasing augmentation probability

# --- tuning ---
tune:
  # Hyperparameters to tune, can override the default values if specified
  # Format: [suggestion_type, [args]]
  # -- float tune args: [min, max, step, log]
  # -- int tune args: [min, max, step, log]
  # -- categorical tune args: [list of options] 

  # Train parameters
  # imgsz: [categorical, [[640, 640], [1024, 544]]]
  batch: [int, [8, 16, 8, false]]  # Use lowercase false for boolean
  lr0: [float, [1e-5, 1e-1, null, true]]  # null instead of None
  lrf: [float, [0.01, 0.1, null]]
  momentum: [float, [0.8, 0.98, null]]
  weight_decay: [float, [0.0, 0.001, null]]
  warmup_epochs: [float, [0.0, 5.0, null]]
  warmup_momentum: [float, [0.6, 0.95, null]]
  warmup_bias_lr: [float, [0.0, 0.2, null]]
  cls: [float, [0.2, 2.0, null]]
  dfl: [float, [1.0, 2.0, null]]

  # Augmentation parameters
  hsv_h: [float, [0.0, 0.1, null]]
  hsv_s: [float, [0.0, 0.9, null]]
  hsv_v: [float, [0.0, 0.9, null]]
  degrees: [float, [0.0, 20.0, null]]
  translate: [float, [0.0, 0.5, null]]
  scale: [float, [0.0, 0.9, null]]
  shear: [float, [0.0, 10.0, null]]
  perspective: [float, [0.0, 0.001, null]]
  flipud: [float, [0.0, 0.5, null]]
  fliplr: [float, [0.0, 1.0, null]]
  bgr: [float, [0.0, 0.0, null]]
  mosaic: [float, [0.8, 1.0, null]]
  mixup: [float, [0.0, 0.5, null]]
  cutmix: [float, [0.0, 0.3, null]]
  copy_paste: [float, [0.0, 0.5, null]]
  copy_paste_mode: [categorical, ['flip', 'mixup']]
  auto_augment: [categorical, ['randaugment', 'autoaugment', 'augmix']]
  erasing: [float, [0.0, 0.2, null]]